#!/usr/bin/env python

import mcr_manipulation_pose_selector_ros.reachability_pose_selector_trigger

if __name__ == '__main__':
    mcr_manipulation_pose_selector_ros.reachability_pose_selector_trigger.main()
